spring.application.name=springChatbot

# 1. MariaDB 설정
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# 데이터베이스 이름, 계정, 비밀번호를 도커 컴포즈 환경변수에서 순수하게 넘겨받음
spring.datasource.url=jdbc:mariadb://db:3306/${DB_NAME}?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# 2. 서버 포트 설정
server.port=8087

# 3. JSP 뷰 경로 설정
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# 4. MyBatis 설정
mybatis.mapper-locations=classpath:mapper/**/*.xml

# 5. 파일 업로드 설정 (Linux 내부 경로)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.location=/app/upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

# 6. FastAPI 엔드포인트 설정
fastapi.url=${FASTAPI_URL}